chore(workflow): improve test workflow (#450)
* chore(workflow): improve test workflow.

utilize docker compose --wait

* chore(workflow): more postgres healthcheck retries

* chore(workflow): quiet pull, postgres healthcheck timeouts

* chore(workflow): retry starting the compose stack

* chore(workflow): clean up docker compose

* chore: trigger pr workflow run

* chore: trigger pr workflow run

* chore(workflow): only log last 500 lines

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -31,18 +31,16 @@ jobs:
       - name: Set up Docker Compose
         run: |
           docker compose build --build-arg GITLAB_MAVEN_REGISTRY_URL="${GITLAB_MAVEN_REGISTRY_URL}"
-          docker compose up -d
-          timeout 150 docker compose logs -f api || true
-      - name: Services health-check API
-        run: |
-          timeout 180 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:9000/swagger-ui/index.html)" != "200" ]]; do sleep 2;echo "."; done'
-          echo "API is up"
+          if ! docker compose up -d --wait --quiet-pull
+          then
+            # retry once to give postgres another chance
+            docker compose up -d --wait --quiet-pull
+          fi
+
+          # debugging
+          docker compose logs api --tail 500
           docker ps
-      - name: Services health-check Keycloak
-        run: |
-          timeout 180 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080/realms/master)" != "200" ]]; do sleep 2;echo "."; done'
-          echo "Keycloak is up"
-          docker ps
+
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
@@ -54,6 +52,10 @@ jobs:
         run: |
           newman run postman/Reeve_Integration.postman_collection.json \
             --environment postman/Reeve_env.postman_environment.json
+
+      - name: Clean up Docker
+        if: always()
+        run: docker compose down -v
 
   playwright:
     runs-on: ubuntu-latest
@@ -72,19 +74,14 @@ jobs:
       - name: Set up Docker Compose
         run: |
           docker compose build --build-arg GITLAB_MAVEN_REGISTRY_URL="${GITLAB_MAVEN_REGISTRY_URL}"
-          docker compose up -d
-          timeout 150 docker compose logs -f api || true
-          
-      - name: Services health-check API
-        run: |
-          timeout 180 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:9000/swagger-ui/index.html)" != "200" ]]; do sleep 2;echo "."; done'
-          echo "API is up"
-          docker ps
+          if ! docker compose up -d --wait --quiet-pull
+          then
+            # retry once to give postgres another chance
+            docker compose up -d --wait --quiet-pull
+          fi
 
-      - name: Services health-check Keycloak
-        run: |
-          timeout 180 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080/realms/master)" != "200" ]]; do sleep 2;echo "."; done'
-          echo "Keycloak is up"
+          # debugging
+          docker compose logs api --tail 500
           docker ps
 
       - name: Set up Node.js
@@ -113,3 +110,7 @@ jobs:
         working-directory: playwright
         run: npm run test
         continue-on-error: true
+
+      - name: Clean up Docker
+        if: always()
+        run: docker compose down -v
